### ISSUE TITLE
How does the speed compare to afl-dynamorio?

### ISSUE THREAD

**Issue by 0xchase** [geeksonsecurity/frida-afl#10]
afl-dynamorio is said to be
> x10-50 slower than Qemu, 25x slower than dyninst - however 10x faster than Pintool

How does frida-afl compare to this?

**Comment by wizche** [comment]
Well I couldnt get the forkserver to work, so its difficult to have a fair comparison, for sure its slower then everything else :)

The main point was to have a tool working on Mac binaries, now there are better solution (TinyInst/Jackalope)
